web: ./pre_deploy.sh && PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
worker: PYTHONPATH=. celery -A app.core.celery_app worker --loglevel=info
beat: PYTHONPATH=. celery -A app.core.celery_app beat --loglevel=info
