/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/me": {
    /** Get User Me */
    get: operations["get_user_me_api_v1_auth_me_get"];
    /** Update User Me */
    patch: operations["update_user_me_api_v1_auth_me_patch"];
  };
  "/api/v1/auth/register": {
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/business/stats": {
    /** Get Business Stats */
    get: operations["get_business_stats_api_v1_business_stats_get"];
  };
  "/api/v1/business/test-chat": {
    /** Test Chat */
    post: operations["test_chat_api_v1_business_test_chat_post"];
  };
  "/api/v1/business/me": {
    /** Get Business Me */
    get: operations["get_business_me_api_v1_business_me_get"];
    /** Create Business Me */
    post: operations["create_business_me_api_v1_business_me_post"];
    /** Update Business Me */
    patch: operations["update_business_me_api_v1_business_me_patch"];
  };
  "/api/v1/business/me/activate-trial": {
    /** Activate Trial */
    post: operations["activate_trial_api_v1_business_me_activate_trial_post"];
  };
  "/api/v1/business/me/assistant": {
    /** Update Assistant Me */
    patch: operations["update_assistant_me_api_v1_business_me_assistant_patch"];
  };
  "/api/v1/integrations/google/authorize": {
    /** Authorize Google */
    get: operations["authorize_google_api_v1_integrations_google_authorize_get"];
  };
  "/api/v1/integrations/google/callback": {
    /** Google Callback */
    get: operations["google_callback_api_v1_integrations_google_callback_get"];
  };
  "/api/v1/integrations/google/availability": {
    /**
     * Get Google Availability
     * @description Fetch availability for the current user's business.
     */
    get: operations["get_google_availability_api_v1_integrations_google_availability_get"];
  };
  "/api/v1/integrations/google/sync": {
    /**
     * Trigger Google Sync
     * @description Manually trigger a calendar sync task.
     */
    post: operations["trigger_google_sync_api_v1_integrations_google_sync_post"];
  };
  "/api/v1/integrations/{provider}": {
    /**
     * Disconnect Integration
     * @description Remove an integration and its associated local cache.
     */
    delete: operations["disconnect_integration_api_v1_integrations__provider__delete"];
  };
  "/api/v1/crm/clients": {
    /** Get Clients */
    get: operations["get_clients_api_v1_crm_clients_get"];
    /** Create Client */
    post: operations["create_client_api_v1_crm_clients_post"];
  };
  "/api/v1/crm/clients/{client_id}": {
    /** Delete Client */
    delete: operations["delete_client_api_v1_crm_clients__client_id__delete"];
    /** Update Client */
    patch: operations["update_client_api_v1_crm_clients__client_id__patch"];
  };
  "/api/v1/crm/appointments": {
    /** Get Appointments */
    get: operations["get_appointments_api_v1_crm_appointments_get"];
    /** Create Appointment */
    post: operations["create_appointment_api_v1_crm_appointments_post"];
  };
  "/api/v1/crm/appointments/{appointment_id}": {
    /** Delete Appointment */
    delete: operations["delete_appointment_api_v1_crm_appointments__appointment_id__delete"];
    /** Update Appointment */
    patch: operations["update_appointment_api_v1_crm_appointments__appointment_id__patch"];
  };
  "/api/v1/services/": {
    /** List Services */
    get: operations["list_services_api_v1_services__get"];
    /** Create Service */
    post: operations["create_service_api_v1_services__post"];
  };
  "/api/v1/services/{service_id}": {
    /** Get Service */
    get: operations["get_service_api_v1_services__service_id__get"];
    /** Delete Service */
    delete: operations["delete_service_api_v1_services__service_id__delete"];
    /** Update Service */
    patch: operations["update_service_api_v1_services__service_id__patch"];
  };
  "/api/v1/whatsapp/webhook": {
    /**
     * Verify Whatsapp
     * @description WhatsApp Webhook verification.
     */
    get: operations["verify_whatsapp_api_v1_whatsapp_webhook_get"];
    /**
     * Whatsapp Webhook
     * @description Receive messages from WhatsApp Cloud API.
     */
    post: operations["whatsapp_webhook_api_v1_whatsapp_webhook_post"];
  };
  "/api/v1/whatsapp/setup": {
    /**
     * Setup Whatsapp
     * @description Save WhatsApp Cloud API credentials.
     */
    post: operations["setup_whatsapp_api_v1_whatsapp_setup_post"];
  };
  "/api/v1/telegram/webhook/{webhook_id}": {
    /**
     * Telegram Webhook
     * @description Receive messages from Telegram via a unique webhook ID.
     */
    post: operations["telegram_webhook_api_v1_telegram_webhook__webhook_id__post"];
  };
  "/api/v1/telegram/link": {
    /**
     * Link Telegram
     * @description Link a Telegram Bot to the current user's business.
     */
    post: operations["link_telegram_api_v1_telegram_link_post"];
  };
  "/api/v1/telegram/status": {
    /**
     * Get Telegram Status
     * @description Check if Telegram is connected.
     */
    get: operations["get_telegram_status_api_v1_telegram_status_get"];
  };
  "/api/v1/telegram/disconnect": {
    /**
     * Disconnect Telegram
     * @description Remove Telegram integration.
     */
    delete: operations["disconnect_telegram_api_v1_telegram_disconnect_delete"];
  };
  "/api/v1/admin/users": {
    /**
     * List Users
     * @description List all users (Admin only).
     */
    get: operations["list_users_api_v1_admin_users_get"];
    /**
     * Create User Admin
     * @description Create a new user (Admin only).
     */
    post: operations["create_user_admin_api_v1_admin_users_post"];
  };
  "/api/v1/admin/users/{user_id}": {
    /**
     * Delete User Admin
     * @description Delete a user (Admin only).
     */
    delete: operations["delete_user_admin_api_v1_admin_users__user_id__delete"];
    /**
     * Update User Admin
     * @description Update a user (Admin only).
     */
    patch: operations["update_user_admin_api_v1_admin_users__user_id__patch"];
  };
  "/api/v1/admin/settings": {
    /**
     * Get Admin Settings
     * @description Fetch all system settings (Admin only).
     */
    get: operations["get_admin_settings_api_v1_admin_settings_get"];
    /**
     * Update Admin Settings
     * @description Update system settings (Admin only).
     */
    post: operations["update_admin_settings_api_v1_admin_settings_post"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AppointmentCreate */
    AppointmentCreate: {
      /** Client Id */
      client_id: string;
      /** Service Id */
      service_id?: string | null;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /**
       * Status
       * @default scheduled
       */
      status?: string;
      /** Notes */
      notes?: string | null;
    };
    /** AppointmentResponse */
    AppointmentResponse: {
      /** Client Id */
      client_id: string;
      /** Service Id */
      service_id?: string | null;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /**
       * Status
       * @default scheduled
       */
      status?: string;
      /** Notes */
      notes?: string | null;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
      /** Google Event Id */
      google_event_id?: string | null;
      client?: components["schemas"]["ClientResponse"] | null;
      service?: components["schemas"]["ServiceResponse"] | null;
    };
    /** AppointmentUpdate */
    AppointmentUpdate: {
      /** Service Id */
      service_id?: string | null;
      /** Start Time */
      start_time?: string | null;
      /** End Time */
      end_time?: string | null;
      /** Status */
      status?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** AssistantConfigResponse */
    AssistantConfigResponse: {
      /** Name */
      name: string;
      /** Tone */
      tone: string;
      /** Greeting */
      greeting: string;
      /**
       * Personalized Greeting
       * @default Hola {name}, ¿en qué puedo ayudarte hoy?
       */
      personalized_greeting?: string;
      /**
       * Logic Template
       * @default standard
       */
      logic_template?: string;
      /** Custom Steps */
      custom_steps?: string | null;
      /**
       * Require Reason
       * @default true
       */
      require_reason?: boolean | null;
      /**
       * Confirm Details
       * @default true
       */
      confirm_details?: boolean | null;
      /**
       * Strict Guardrails
       * @default true
       */
      strict_guardrails?: boolean | null;
      /**
       * Enable Honesty
       * @default true
       */
      enable_honesty?: boolean;
      /**
       * Enable Internal Alert
       * @default false
       */
      enable_internal_alert?: boolean;
      /**
       * Enable Lead Capture
       * @default true
       */
      enable_lead_capture?: boolean;
      /**
       * Enable Emergency Phone
       * @default false
       */
      enable_emergency_phone?: boolean;
      /** Working Hours */
      working_hours?: {
        [key: string]: string[];
      } | null;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
    };
    /** AssistantConfigUpdate */
    AssistantConfigUpdate: {
      /** Name */
      name?: string | null;
      /** Tone */
      tone?: string | null;
      /** Greeting */
      greeting?: string | null;
      /** Personalized Greeting */
      personalized_greeting?: string | null;
      /** Logic Template */
      logic_template?: string | null;
      /** Custom Steps */
      custom_steps?: string | null;
      /** Require Reason */
      require_reason?: boolean | null;
      /** Confirm Details */
      confirm_details?: boolean | null;
      /** Strict Guardrails */
      strict_guardrails?: boolean | null;
      /** Enable Honesty */
      enable_honesty?: boolean | null;
      /** Enable Internal Alert */
      enable_internal_alert?: boolean | null;
      /** Enable Lead Capture */
      enable_lead_capture?: boolean | null;
      /** Enable Emergency Phone */
      enable_emergency_phone?: boolean | null;
      /** Working Hours */
      working_hours?: {
        [key: string]: string[];
      } | null;
    };
    /** Body_login_api_v1_auth_login_post */
    Body_login_api_v1_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** BusinessProfileCreate */
    BusinessProfileCreate: {
      /** Name */
      name: string;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
      /**
       * Timezone
       * @default UTC
       */
      timezone?: string;
    };
    /** BusinessProfileResponse */
    BusinessProfileResponse: {
      /** Name */
      name: string;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
      /**
       * Timezone
       * @default UTC
       */
      timezone?: string;
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Trial Expires At */
      trial_expires_at?: string | null;
      /** Is Active */
      is_active: boolean;
      assistant_config?: components["schemas"]["AssistantConfigResponse"] | null;
      /**
       * Integrations
       * @default []
       */
      integrations?: components["schemas"]["IntegrationResponse"][];
    };
    /** BusinessProfileUpdate */
    BusinessProfileUpdate: {
      /** Name */
      name?: string | null;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
      /** Timezone */
      timezone?: string | null;
    };
    /** ClientCreate */
    ClientCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /**
       * Custom Fields
       * @default {}
       */
      custom_fields?: {
        [key: string]: unknown;
      } | null;
    };
    /** ClientResponse */
    ClientResponse: {
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /**
       * Custom Fields
       * @default {}
       */
      custom_fields?: {
        [key: string]: unknown;
      } | null;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
      /** Telegram Id Hash */
      telegram_id_hash?: string | null;
      /** Whatsapp Id Hash */
      whatsapp_id_hash?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ClientUpdate */
    ClientUpdate: {
      /** Name */
      name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Custom Fields */
      custom_fields?: {
        [key: string]: unknown;
      } | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IntegrationResponse */
    IntegrationResponse: {
      /** Id */
      id: string;
      /** Provider */
      provider: string;
      /** Settings */
      settings?: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ServiceCreate */
    ServiceCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Duration Minutes
       * @default 60
       */
      duration_minutes?: number;
      /** Price */
      price?: string | null;
      /**
       * Attributes
       * @default {}
       */
      attributes?: {
        [key: string]: unknown;
      } | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
    };
    /** ServiceResponse */
    ServiceResponse: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Duration Minutes
       * @default 60
       */
      duration_minutes?: number;
      /** Price */
      price?: string | null;
      /**
       * Attributes
       * @default {}
       */
      attributes?: {
        [key: string]: unknown;
      } | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ServiceUpdate */
    ServiceUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Duration Minutes */
      duration_minutes?: number | null;
      /** Price */
      price?: string | null;
      /** Attributes */
      attributes?: {
        [key: string]: unknown;
      } | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** TestChatRequest */
    TestChatRequest: {
      /** Message */
      message: string;
      assistant_config?: components["schemas"]["AssistantConfigUpdate"] | null;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** UserCreateAdmin */
    UserCreateAdmin: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /**
       * Role
       * @default member
       */
      role?: string;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /**
       * Is Admin
       * @default false
       */
      is_admin?: boolean;
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: string;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean | null;
      /**
       * Is Admin
       * @default false
       */
      is_admin?: boolean | null;
      /**
       * Role
       * @default member
       */
      role?: string | null;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Email */
      email?: string | null;
      /** Password */
      password?: string | null;
      /** Role */
      role?: string | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get User Me */
  get_user_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /** Update User Me */
  update_user_me_api_v1_auth_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Business Stats */
  get_business_stats_api_v1_business_stats_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Test Chat */
  test_chat_api_v1_business_test_chat_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Business Me */
  get_business_me_api_v1_business_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
    };
  };
  /** Create Business Me */
  create_business_me_api_v1_business_me_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessProfileCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Business Me */
  update_business_me_api_v1_business_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessProfileUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Activate Trial */
  activate_trial_api_v1_business_me_activate_trial_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
    };
  };
  /** Update Assistant Me */
  update_assistant_me_api_v1_business_me_assistant_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssistantConfigUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Authorize Google */
  authorize_google_api_v1_integrations_google_authorize_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Google Callback */
  google_callback_api_v1_integrations_google_callback_get: {
    parameters: {
      query: {
        state: string;
        code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Google Availability
   * @description Fetch availability for the current user's business.
   */
  get_google_availability_api_v1_integrations_google_availability_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Trigger Google Sync
   * @description Manually trigger a calendar sync task.
   */
  trigger_google_sync_api_v1_integrations_google_sync_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Disconnect Integration
   * @description Remove an integration and its associated local cache.
   */
  disconnect_integration_api_v1_integrations__provider__delete: {
    parameters: {
      path: {
        provider: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Clients */
  get_clients_api_v1_crm_clients_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientResponse"][];
        };
      };
    };
  };
  /** Create Client */
  create_client_api_v1_crm_clients_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Client */
  delete_client_api_v1_crm_clients__client_id__delete: {
    parameters: {
      path: {
        client_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Client */
  update_client_api_v1_crm_clients__client_id__patch: {
    parameters: {
      path: {
        client_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Appointments */
  get_appointments_api_v1_crm_appointments_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponse"][];
        };
      };
    };
  };
  /** Create Appointment */
  create_appointment_api_v1_crm_appointments_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Appointment */
  delete_appointment_api_v1_crm_appointments__appointment_id__delete: {
    parameters: {
      path: {
        appointment_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Appointment */
  update_appointment_api_v1_crm_appointments__appointment_id__patch: {
    parameters: {
      path: {
        appointment_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Services */
  list_services_api_v1_services__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceResponse"][];
        };
      };
    };
  };
  /** Create Service */
  create_service_api_v1_services__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Service */
  get_service_api_v1_services__service_id__get: {
    parameters: {
      path: {
        service_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Service */
  delete_service_api_v1_services__service_id__delete: {
    parameters: {
      path: {
        service_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Service */
  update_service_api_v1_services__service_id__patch: {
    parameters: {
      path: {
        service_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Verify Whatsapp
   * @description WhatsApp Webhook verification.
   */
  verify_whatsapp_api_v1_whatsapp_webhook_get: {
    parameters: {
      query?: {
        "hub.mode"?: string;
        "hub.verify_token"?: string;
        "hub.challenge"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Whatsapp Webhook
   * @description Receive messages from WhatsApp Cloud API.
   */
  whatsapp_webhook_api_v1_whatsapp_webhook_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Setup Whatsapp
   * @description Save WhatsApp Cloud API credentials.
   */
  setup_whatsapp_api_v1_whatsapp_setup_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Telegram Webhook
   * @description Receive messages from Telegram via a unique webhook ID.
   */
  telegram_webhook_api_v1_telegram_webhook__webhook_id__post: {
    parameters: {
      path: {
        webhook_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Link Telegram
   * @description Link a Telegram Bot to the current user's business.
   */
  link_telegram_api_v1_telegram_link_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Telegram Status
   * @description Check if Telegram is connected.
   */
  get_telegram_status_api_v1_telegram_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Disconnect Telegram
   * @description Remove Telegram integration.
   */
  disconnect_telegram_api_v1_telegram_disconnect_delete: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Users
   * @description List all users (Admin only).
   */
  list_users_api_v1_admin_users_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"][];
        };
      };
    };
  };
  /**
   * Create User Admin
   * @description Create a new user (Admin only).
   */
  create_user_admin_api_v1_admin_users_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreateAdmin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete User Admin
   * @description Delete a user (Admin only).
   */
  delete_user_admin_api_v1_admin_users__user_id__delete: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update User Admin
   * @description Update a user (Admin only).
   */
  update_user_admin_api_v1_admin_users__user_id__patch: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Admin Settings
   * @description Fetch all system settings (Admin only).
   */
  get_admin_settings_api_v1_admin_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * Update Admin Settings
   * @description Update system settings (Admin only).
   */
  update_admin_settings_api_v1_admin_settings_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: string;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
