/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/me": {
    /** Get User Me */
    get: operations["get_user_me_api_v1_auth_me_get"];
    /** Update User Me */
    patch: operations["update_user_me_api_v1_auth_me_patch"];
  };
  "/api/v1/auth/register": {
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/business/me": {
    /** Get Business Me */
    get: operations["get_business_me_api_v1_business_me_get"];
    /** Create Business Me */
    post: operations["create_business_me_api_v1_business_me_post"];
    /** Update Business Me */
    patch: operations["update_business_me_api_v1_business_me_patch"];
  };
  "/api/v1/business/me/assistant": {
    /** Update Assistant Me */
    patch: operations["update_assistant_me_api_v1_business_me_assistant_patch"];
  };
  "/api/v1/integrations/google/authorize": {
    /** Authorize Google */
    get: operations["authorize_google_api_v1_integrations_google_authorize_get"];
  };
  "/api/v1/integrations/google/callback": {
    /** Google Callback */
    get: operations["google_callback_api_v1_integrations_google_callback_get"];
  };
  "/api/v1/integrations/google/availability": {
    /**
     * Get Google Availability
     * @description Fetch availability for the current user's business.
     */
    get: operations["get_google_availability_api_v1_integrations_google_availability_get"];
  };
  "/api/v1/crm/clients": {
    /** Get Clients */
    get: operations["get_clients_api_v1_crm_clients_get"];
    /** Create Client */
    post: operations["create_client_api_v1_crm_clients_post"];
  };
  "/api/v1/crm/appointments": {
    /** Get Appointments */
    get: operations["get_appointments_api_v1_crm_appointments_get"];
    /** Create Appointment */
    post: operations["create_appointment_api_v1_crm_appointments_post"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AppointmentCreate */
    AppointmentCreate: {
      /** Client Id */
      client_id: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /**
       * Status
       * @default scheduled
       */
      status?: string;
    };
    /** AppointmentResponse */
    AppointmentResponse: {
      /** Client Id */
      client_id: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /**
       * Status
       * @default scheduled
       */
      status?: string;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
      /** Google Event Id */
      google_event_id?: string | null;
      client?: components["schemas"]["ClientResponse"] | null;
    };
    /** AssistantConfigResponse */
    AssistantConfigResponse: {
      /** Name */
      name: string;
      /** Tone */
      tone: string;
      /** Greeting */
      greeting: string;
      /** Working Hours */
      working_hours?: {
        [key: string]: string[];
      } | null;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
    };
    /** AssistantConfigUpdate */
    AssistantConfigUpdate: {
      /** Name */
      name?: string | null;
      /** Tone */
      tone?: string | null;
      /** Greeting */
      greeting?: string | null;
      /** Working Hours */
      working_hours?: {
        [key: string]: string[];
      } | null;
    };
    /** Body_login_api_v1_auth_login_post */
    Body_login_api_v1_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** BusinessProfileCreate */
    BusinessProfileCreate: {
      /** Name */
      name: string;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
    };
    /** BusinessProfileResponse */
    BusinessProfileResponse: {
      /** Name */
      name: string;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Trial Expires At */
      trial_expires_at?: string | null;
      /** Is Active */
      is_active: boolean;
      assistant_config?: components["schemas"]["AssistantConfigResponse"] | null;
      /**
       * Integrations
       * @default []
       */
      integrations?: components["schemas"]["IntegrationResponse"][];
    };
    /** BusinessProfileUpdate */
    BusinessProfileUpdate: {
      /** Name */
      name?: string | null;
      /** Category */
      category?: string | null;
      /** Contact Phone */
      contact_phone?: string | null;
    };
    /** ClientCreate */
    ClientCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Email */
      email?: string | null;
    };
    /** ClientResponse */
    ClientResponse: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Email */
      email?: string | null;
      /** Id */
      id: string;
      /** Business Id */
      business_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IntegrationResponse */
    IntegrationResponse: {
      /** Id */
      id: string;
      /** Provider */
      provider: string;
      /** Settings */
      settings?: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: string;
      /** Is Active */
      is_active: boolean;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Email */
      email?: string | null;
      /** Password */
      password?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get User Me */
  get_user_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /** Update User Me */
  update_user_me_api_v1_auth_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Business Me */
  get_business_me_api_v1_business_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
    };
  };
  /** Create Business Me */
  create_business_me_api_v1_business_me_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessProfileCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Business Me */
  update_business_me_api_v1_business_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessProfileUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Assistant Me */
  update_assistant_me_api_v1_business_me_assistant_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssistantConfigUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BusinessProfileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Authorize Google */
  authorize_google_api_v1_integrations_google_authorize_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Google Callback */
  google_callback_api_v1_integrations_google_callback_get: {
    parameters: {
      query: {
        state: string;
        code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Google Availability
   * @description Fetch availability for the current user's business.
   */
  get_google_availability_api_v1_integrations_google_availability_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Clients */
  get_clients_api_v1_crm_clients_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientResponse"][];
        };
      };
    };
  };
  /** Create Client */
  create_client_api_v1_crm_clients_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Appointments */
  get_appointments_api_v1_crm_appointments_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponse"][];
        };
      };
    };
  };
  /** Create Appointment */
  create_appointment_api_v1_crm_appointments_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
