"""Add B2B Sales Intelligence models

Revision ID: 091707792b94
Revises: 771c9a5cf6e5
Create Date: 2026-05-27 15:52:17.263576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '091707792b94'
down_revision: Union[str, None] = '771c9a5cf6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get current database state to prevent DuplicateTableError
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'categories' not in existing_tables:
        op.create_table('categories',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('business_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    
    if 'stores' not in existing_tables:
        op.create_table('stores',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('business_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('market', sa.String(), nullable=True),
        sa.Column('segment', sa.String(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('opening_date', sa.Date(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    
    if 'competitors' not in existing_tables:
        op.create_table('competitors',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('market_share', sa.String(), nullable=True),
        sa.Column('strengths', sa.Text(), nullable=True),
        sa.Column('weaknesses', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    
    if 'customers' not in existing_tables:
        op.create_table('customers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('birthday', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(), nullable=True),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('whatsapp_id', sa.String(), nullable=True),
        sa.Column('custom_fields', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
        op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    
    if 'products' not in existing_tables:
        op.create_table('products',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('sku', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    
    if 'store_notes' not in existing_tables:
        op.create_table('store_notes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('risks', sa.Text(), nullable=True),
        sa.Column('opportunities', sa.Text(), nullable=True),
        sa.Column('preferred_actions', sa.Text(), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_store_notes_id'), 'store_notes', ['id'], unique=False)
    
    if 'customer_notes' not in existing_tables:
        op.create_table('customer_notes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=False),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('comm_style', sa.String(), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_customer_notes_id'), 'customer_notes', ['id'], unique=False)
    
    if 'orders' not in existing_tables:
        op.create_table('orders',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('total_price', sa.Float(), nullable=True),
        sa.Column('order_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    
    # Check columns for appointments before adding
    appointment_columns = [col['name'] for col in inspector.get_columns('appointments')]
    if 'store_id' not in appointment_columns:
        op.add_column('appointments', sa.Column('store_id', sa.String(), nullable=True))
    if 'customer_id' not in appointment_columns:
        op.add_column('appointments', sa.Column('customer_id', sa.String(), nullable=True))
    
    op.alter_column('appointments', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Conditional drop indexes
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('appointments')]
    for idx in ['ix_appointments_business_id_start_time', 'ix_appointments_end_time', 'ix_appointments_start_time']:
        if idx in existing_indexes:
            op.drop_index(idx, table_name='appointments')
            
    # Foreign keys
    existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('appointments')]
    # Alembic creates generic names if None, let's just try/catch or skip if columns are linked
    try:
        op.create_foreign_key(None, 'appointments', 'stores', ['store_id'], ['id'])
        op.create_foreign_key(None, 'appointments', 'customers', ['customer_id'], ['id'])
    except Exception: pass

    # Busy slots
    busy_indexes = [idx['name'] for idx in inspector.get_indexes('busy_slots')]
    for idx in ['ix_busy_slots_business_id_start_time', 'ix_busy_slots_end_time', 'ix_busy_slots_start_time']:
        if idx in busy_indexes:
            op.drop_index(idx, table_name='busy_slots')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_busy_slots_start_time', 'busy_slots', ['start_time'], unique=False)
    op.create_index('ix_busy_slots_end_time', 'busy_slots', ['end_time'], unique=False)
    op.create_index('ix_busy_slots_business_id_start_time', 'busy_slots', ['business_id', 'start_time'], unique=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_index('ix_appointments_start_time', 'appointments', ['start_time'], unique=False)
    op.create_index('ix_appointments_end_time', 'appointments', ['end_time'], unique=False)
    op.create_index('ix_appointments_business_id_start_time', 'appointments', ['business_id', 'start_time'], unique=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('appointments', 'customer_id')
    op.drop_column('appointments', 'store_id')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_notes_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_store_notes_id'), table_name='store_notes')
    op.drop_table('store_notes')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
