"""Add routing_config to BusinessProfile

Revision ID: 10ffac29c01f
Revises: 40f7bcbc34a1
Create Date: 2026-06-24 16:55:41.050504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ffac29c01f'
down_revision: Union[str, None] = '40f7bcbc34a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('routing_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'routing_config')
    # ### end Alembic commands ###
