"""add_client_id_to_store

Revision ID: 18ca30515994
Revises: 44af8f82f483
Create Date: 2026-05-25 15:20:01.965120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ca30515994'
down_revision: Union[str, None] = '44af8f82f483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_stores_client_id_clients', 'stores', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stores_client_id_clients', 'stores', type_='foreignkey')
    op.drop_column('stores', 'client_id')
    # ### end Alembic commands ###
