"""add_behavioral_toggles_to_assistant_config

Revision ID: 1c65f6cb21a3
Revises: ee4e0f927f36
Create Date: 2026-03-23 21:09:57.210582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c65f6cb21a3'
down_revision: Union[str, None] = 'ee4e0f927f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_configs', sa.Column('enable_honesty', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('enable_internal_alert', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('enable_lead_capture', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('enable_emergency_phone', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE assistant_configs SET enable_honesty = true, enable_internal_alert = false, enable_lead_capture = true, enable_emergency_phone = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_configs', 'enable_emergency_phone')
    op.drop_column('assistant_configs', 'enable_lead_capture')
    op.drop_column('assistant_configs', 'enable_internal_alert')
    op.drop_column('assistant_configs', 'enable_honesty')
    # ### end Alembic commands ###
