"""Add BusySlot table

Revision ID: 1d0c07b72f11
Revises: 4653c07ccecb
Create Date: 2026-03-06 13:09:21.820899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0c07b72f11'
down_revision: Union[str, None] = '4653c07ccecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busy_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busy_slots_external_id'), 'busy_slots', ['external_id'], unique=False)
    op.create_index(op.f('ix_busy_slots_id'), 'busy_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_busy_slots_id'), table_name='busy_slots')
    op.drop_index(op.f('ix_busy_slots_external_id'), table_name='busy_slots')
    op.drop_table('busy_slots')
    # ### end Alembic commands ###
