"""add custom_steps to assistant_config

Revision ID: 2280b1477554
Revises: fb2785c9380a
Create Date: 2026-03-17 18:45:54.974506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2280b1477554'
down_revision: Union[str, None] = 'fb2785c9380a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_configs', sa.Column('custom_steps', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_configs', 'custom_steps')
    # ### end Alembic commands ###
