"""fix unique constraints and add searchable hashes for pii

Revision ID: 26002a4661e1
Revises: 31605e9df8e5
Create Date: 2026-03-17 16:00:27.317056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26002a4661e1'
down_revision: Union[str, None] = '31605e9df8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('telegram_id_hash', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('whatsapp_id_hash', sa.String(), nullable=True))
    op.drop_index('ix_clients_telegram_id', table_name='clients')
    op.drop_index('ix_clients_whatsapp_id', table_name='clients')
    op.create_unique_constraint('_business_telegram_hash_uc', 'clients', ['business_id', 'telegram_id_hash'])
    op.create_unique_constraint('_business_whatsapp_hash_uc', 'clients', ['business_id', 'whatsapp_id_hash'])
    op.create_index(op.f('ix_clients_telegram_id_hash'), 'clients', ['telegram_id_hash'], unique=False)
    op.create_index(op.f('ix_clients_whatsapp_id_hash'), 'clients', ['whatsapp_id_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_whatsapp_id_hash'), table_name='clients')
    op.drop_index(op.f('ix_clients_telegram_id_hash'), table_name='clients')
    op.drop_constraint('_business_whatsapp_hash_uc', 'clients', type_='unique')
    op.drop_constraint('_business_telegram_hash_uc', 'clients', type_='unique')
    op.create_index('ix_clients_whatsapp_id', 'clients', ['whatsapp_id'], unique=True)
    op.create_index('ix_clients_telegram_id', 'clients', ['telegram_id'], unique=True)
    op.drop_column('clients', 'whatsapp_id_hash')
    op.drop_column('clients', 'telegram_id_hash')
    # ### end Alembic commands ###
