"""fix unique constraints and add searchable hashes for pii

Revision ID: 26002a4661e1
Revises: 31605e9df8e5
Create Date: 2026-03-17 16:00:27.317056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26002a4661e1'
down_revision: Union[str, None] = '31605e9df8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import hashlib
from app.core.security import encrypt_token

def upgrade() -> None:
    # 1. Add columns
    op.add_column('clients', sa.Column('telegram_id_hash', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('whatsapp_id_hash', sa.String(), nullable=True))

    # 2. Data Migration: Populate hashes and encrypt existing IDs
    connection = op.get_bind()
    # Fetch all clients with messaging IDs
    results = connection.execute(
        sa.text("SELECT id, telegram_id, whatsapp_id FROM clients WHERE telegram_id IS NOT NULL OR whatsapp_id IS NOT NULL")
    ).fetchall()
    
    for row in results:
        client_id = row[0]
        tg_id = row[1]
        wa_id = row[2]
        
        updates = {}
        if tg_id and not tg_id.startswith("gAAAA"): # Only if not already encrypted
            updates["telegram_id"] = encrypt_token(tg_id)
            updates["telegram_id_hash"] = hashlib.sha256(tg_id.encode()).hexdigest()
        elif tg_id:
            # If it was already encrypted by some chance, we can't easily hash it without decrypting
            # but usually it's plain text if it's "lost" now.
            pass

        if wa_id and not wa_id.startswith("gAAAA"):
            updates["whatsapp_id"] = encrypt_token(wa_id)
            updates["whatsapp_id_hash"] = hashlib.sha256(wa_id.encode()).hexdigest()
            
        if updates:
            set_clause = ", ".join([f"{k} = :{k}" for k in updates.keys()])
            connection.execute(
                sa.text(f"UPDATE clients SET {set_clause} WHERE id = :id"),
                {"id": client_id, **updates}
            )

    # 3. Finalize schema
    op.drop_index('ix_clients_telegram_id', table_name='clients')
    op.drop_index('ix_clients_whatsapp_id', table_name='clients')
    op.create_unique_constraint('_business_telegram_hash_uc', 'clients', ['business_id', 'telegram_id_hash'])
    op.create_unique_constraint('_business_whatsapp_hash_uc', 'clients', ['business_id', 'whatsapp_id_hash'])
    op.create_index(op.f('ix_clients_telegram_id_hash'), 'clients', ['telegram_id_hash'], unique=False)
    op.create_index(op.f('ix_clients_whatsapp_id_hash'), 'clients', ['whatsapp_id_hash'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_whatsapp_id_hash'), table_name='clients')
    op.drop_index(op.f('ix_clients_telegram_id_hash'), table_name='clients')
    op.drop_constraint('_business_whatsapp_hash_uc', 'clients', type_='unique')
    op.drop_constraint('_business_telegram_hash_uc', 'clients', type_='unique')
    op.create_index('ix_clients_whatsapp_id', 'clients', ['whatsapp_id'], unique=True)
    op.create_index('ix_clients_telegram_id', 'clients', ['telegram_id'], unique=True)
    op.drop_column('clients', 'whatsapp_id_hash')
    op.drop_column('clients', 'telegram_id_hash')
    # ### end Alembic commands ###
