"""Hardened Catalog models with draft fields

Revision ID: 2714c91cdb74
Revises: 3069c93aaae3
Create Date: 2026-06-07 13:34:21.009925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2714c91cdb74'
down_revision: Union[str, None] = '3069c93aaae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modified to be idempotent due to surgical_rebuild.py running create_all
    op.execute("ALTER TABLE categories ADD COLUMN IF NOT EXISTS category_type VARCHAR")
    op.execute("ALTER TABLE categories ADD COLUMN IF NOT EXISTS external_id VARCHAR")
    op.execute("CREATE INDEX IF NOT EXISTS ix_categories_category_type ON categories (category_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_categories_external_id ON categories (external_id)")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_id VARCHAR")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_date DATE")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_address VARCHAR")
    op.execute("CREATE INDEX IF NOT EXISTS ix_orders_delivery_id ON orders (delivery_id)")
    op.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type VARCHAR")
    op.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS brand VARCHAR")
    op.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_of_measure VARCHAR")
    op.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS external_id VARCHAR")
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_brand ON products (brand)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_external_id ON products (external_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_product_type ON products (product_type)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modified to be idempotent
    op.execute("DROP INDEX IF EXISTS ix_products_product_type")
    op.execute("DROP INDEX IF EXISTS ix_products_external_id")
    op.execute("DROP INDEX IF EXISTS ix_products_brand")
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS external_id")
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS unit_of_measure")
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS brand")
    op.execute("ALTER TABLE products DROP COLUMN IF EXISTS product_type")
    op.execute("DROP INDEX IF EXISTS ix_orders_delivery_id")
    op.execute("ALTER TABLE orders DROP COLUMN IF EXISTS shipping_address")
    op.execute("ALTER TABLE orders DROP COLUMN IF EXISTS payment_method")
    op.execute("ALTER TABLE orders DROP COLUMN IF EXISTS delivery_date")
    op.execute("ALTER TABLE orders DROP COLUMN IF EXISTS delivery_id")
    op.execute("DROP INDEX IF EXISTS ix_categories_external_id")
    op.execute("DROP INDEX IF EXISTS ix_categories_category_type")
    op.execute("ALTER TABLE categories DROP COLUMN IF EXISTS external_id")
    op.execute("ALTER TABLE categories DROP COLUMN IF EXISTS category_type")
    # ### end Alembic commands ###
