"""Hardened Catalog models with draft fields

Revision ID: 2714c91cdb74
Revises: 3069c93aaae3
Create Date: 2026-06-07 13:34:21.009925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2714c91cdb74'
down_revision: Union[str, None] = '3069c93aaae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_type', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_external_id'), 'categories', ['external_id'], unique=False)
    op.add_column('orders', sa.Column('delivery_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_delivery_id'), 'orders', ['delivery_id'], unique=False)
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit_of_measure', sa.String(), nullable=True))
    op.add_column('products', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'external_id')
    op.drop_column('products', 'unit_of_measure')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'product_type')
    op.drop_index(op.f('ix_orders_delivery_id'), table_name='orders')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_date')
    op.drop_column('orders', 'delivery_id')
    op.drop_index(op.f('ix_categories_external_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_column('categories', 'external_id')
    op.drop_column('categories', 'category_type')
    # ### end Alembic commands ###
