"""add_b2b_schema_hardening_fields

Revision ID: 3069c93aaae3
Revises: 5d81ee258a95
Create Date: 2026-05-29 13:28:55.365481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3069c93aaae3'
down_revision: Union[str, None] = '5d81ee258a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_table('customers')
    op.create_index('ix_appointments_business_id_start_time', 'appointments', ['business_id', 'start_time'], unique=False)
    op.drop_column('appointments', 'store_id')
    op.drop_column('appointments', 'customer_id')
    op.alter_column('business_profiles', 'vertical_type',
               existing_type=postgresql.ENUM('BASIC', 'TRADE', name='verticaltype'),
               nullable=False,
               existing_server_default=sa.text("'BASIC'::verticaltype"))
    op.create_index('ix_busy_slots_business_id_start_time', 'busy_slots', ['business_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_end_time'), 'busy_slots', ['end_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_start_time'), 'busy_slots', ['start_time'], unique=False)
    op.add_column('clients', sa.Column('role', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('address', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('market', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('region', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('competitors', sa.Column('weaknesses', sa.Text(), nullable=True))
    op.create_index('ix_competitors_business_market', 'competitors', ['business_id', 'market'], unique=False)
    op.create_index('ix_competitors_business_region', 'competitors', ['business_id', 'region'], unique=False)
    op.create_index(op.f('ix_competitors_market'), 'competitors', ['market'], unique=False)
    op.create_index(op.f('ix_competitors_region'), 'competitors', ['region'], unique=False)
    op.add_column('customer_notes', sa.Column('last_visit_date', sa.Date(), nullable=True))
    op.add_column('customer_notes', sa.Column('next_visit_date', sa.Date(), nullable=True))
    op.add_column('store_notes', sa.Column('execution_level', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('email', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('market', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('segment', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('region', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('opening_date', sa.Date(), nullable=True))
    op.create_index('ix_stores_business_market', 'stores', ['business_id', 'market'], unique=False)
    op.create_index('ix_stores_business_region', 'stores', ['business_id', 'region'], unique=False)
    op.create_index(op.f('ix_stores_market'), 'stores', ['market'], unique=False)
    op.create_index(op.f('ix_stores_region'), 'stores', ['region'], unique=False)
    op.create_index(op.f('ix_stores_segment'), 'stores', ['segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_segment'), table_name='stores')
    op.drop_index(op.f('ix_stores_region'), table_name='stores')
    op.drop_index(op.f('ix_stores_market'), table_name='stores')
    op.drop_index('ix_stores_business_region', table_name='stores')
    op.drop_index('ix_stores_business_market', table_name='stores')
    op.drop_column('stores', 'opening_date')
    op.drop_column('stores', 'region')
    op.drop_column('stores', 'segment')
    op.drop_column('stores', 'market')
    op.drop_column('stores', 'email')
    op.drop_column('stores', 'phone')
    op.drop_column('store_notes', 'execution_level')
    op.drop_column('customer_notes', 'next_visit_date')
    op.drop_column('customer_notes', 'last_visit_date')
    op.drop_index(op.f('ix_competitors_region'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_market'), table_name='competitors')
    op.drop_index('ix_competitors_business_region', table_name='competitors')
    op.drop_index('ix_competitors_business_market', table_name='competitors')
    op.drop_column('competitors', 'weaknesses')
    op.drop_column('competitors', 'strengths')
    op.drop_column('competitors', 'region')
    op.drop_column('competitors', 'market')
    op.drop_column('competitors', 'address')
    op.drop_column('competitors', 'phone')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'birthday')
    op.drop_column('clients', 'role')
    op.drop_index(op.f('ix_busy_slots_start_time'), table_name='busy_slots')
    op.drop_index(op.f('ix_busy_slots_end_time'), table_name='busy_slots')
    op.drop_index('ix_busy_slots_business_id_start_time', table_name='busy_slots')
    op.alter_column('business_profiles', 'vertical_type',
               existing_type=postgresql.ENUM('BASIC', 'TRADE', name='verticaltype'),
               nullable=True,
               existing_server_default=sa.text("'BASIC'::verticaltype"))
    op.add_column('appointments', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_appointments_business_id_start_time', table_name='appointments')
    op.create_table('customers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    # ### end Alembic commands ###
