"""add_whatsapp_opt_in_to_client

Revision ID: 3854dadb6a75
Revises: fe805ab06981
Create Date: 2026-06-26 16:13:01.084117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3854dadb6a75'
down_revision: Union[str, None] = 'fe805ab06981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('clients', sa.Column('whatsapp_opt_in_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'whatsapp_opt_in_at')
    op.drop_column('clients', 'whatsapp_opt_in')
    # ### end Alembic commands ###
