"""add_wholesale_threshold_to_product

Revision ID: 40f7bcbc34a1
Revises: fe412c1df3d4
Create Date: 2026-06-24 16:09:05.597944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40f7bcbc34a1'
down_revision: Union[str, None] = 'fe412c1df3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('wholesale_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'wholesale_threshold')
    # ### end Alembic commands ###
