"""add_trade_competitors_and_customer_notes

Revision ID: 44af8f82f483
Revises: 5ee6d1ad3979
Create Date: 2026-05-25 14:25:29.994946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44af8f82f483'
down_revision: Union[str, None] = '5ee6d1ad3979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get current database state to prevent DuplicateTableError
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'competitors' not in existing_tables:
        op.create_table('competitors',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('business_id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('presence_level', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
        op.create_index(op.f('ix_competitors_name'), 'competitors', ['name'], unique=False)
    
    if 'customer_notes' not in existing_tables:
        op.create_table('customer_notes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('business_id', sa.String(), nullable=False),
        sa.Column('client_id', sa.String(), nullable=False),
        sa.Column('comm_style', sa.String(), nullable=True),
        sa.Column('visit_frequency', sa.String(), nullable=True),
        sa.Column('preferred_actions', sa.Text(), nullable=True),
        sa.Column('general_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_customer_notes_id'), 'customer_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_notes_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_competitors_name'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
