"""refactor_store_clients_to_many_to_many

Revision ID: 475768df9d70
Revises: 4cf7b82a61ea
Create Date: 2026-05-26 14:30:04.590775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475768df9d70'
down_revision: Union[str, None] = '4cf7b82a61ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_clients',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'client_id')
    )
    op.drop_constraint('fk_stores_client_id_clients', 'stores', type_='foreignkey')
    op.drop_column('stores', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_stores_client_id_clients', 'stores', 'clients', ['client_id'], ['id'])
    op.drop_table('store_clients')
    # ### end Alembic commands ###
