"""remove_redundant_contact_fields_from_store

Revision ID: 4cf7b82a61ea
Revises: 18ca30515994
Create Date: 2026-05-26 12:18:31.538843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf7b82a61ea'
down_revision: Union[str, None] = '18ca30515994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'contact_phone')
    op.drop_column('stores', 'contact_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
