"""Add embedding columns to Store Client and Competitor

Revision ID: 5545550b117f
Revises: 2714c91cdb74
Create Date: 2026-06-07 13:41:41.402066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5545550b117f'
down_revision: Union[str, None] = '2714c91cdb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    op.add_column('competitors', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    op.add_column('stores', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'embedding')
    op.drop_column('competitors', 'embedding')
    op.drop_column('clients', 'embedding')
    # ### end Alembic commands ###
