"""Add vertical type to business profile

Revision ID: 6263dde0c255
Revises: ef488a1580aa
Create Date: 2026-05-27 16:51:49.731949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6263dde0c255'
down_revision: Union[str, None] = 'ef488a1580aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('greeting', sa.String(), nullable=False),
    sa.Column('personalized_greeting', sa.String(), nullable=False),
    sa.Column('logic_template', sa.String(), nullable=False),
    sa.Column('custom_steps', sa.String(), nullable=True),
    sa.Column('require_reason', sa.Boolean(), nullable=True),
    sa.Column('confirm_details', sa.Boolean(), nullable=True),
    sa.Column('strict_guardrails', sa.Boolean(), nullable=True),
    sa.Column('enable_honesty', sa.Boolean(), nullable=True),
    sa.Column('enable_internal_alert', sa.Boolean(), nullable=True),
    sa.Column('enable_lead_capture', sa.Boolean(), nullable=True),
    sa.Column('enable_emergency_phone', sa.Boolean(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_id'), 'data_imports', ['id'], unique=False)
    op.create_table('store_clients',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'client_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_assistant_configs_id', table_name='assistant_configs')
    op.drop_table('assistant_configs')
    op.create_index('ix_appointments_business_id_start_time', 'appointments', ['business_id', 'start_time'], unique=False)
    op.drop_constraint('appointments_customer_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_store_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'store_id')
    op.drop_column('appointments', 'customer_id')
    op.add_column('business_profiles', sa.Column('vertical_type', sa.Enum('BASIC', 'TRADE', name='verticaltype'), server_default='BASIC', nullable=False))
    op.create_index('ix_busy_slots_business_id_start_time', 'busy_slots', ['business_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_end_time'), 'busy_slots', ['end_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_start_time'), 'busy_slots', ['start_time'], unique=False)
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('categories', 'type')
    op.add_column('competitors', sa.Column('business_id', sa.String(), nullable=False))
    op.add_column('competitors', sa.Column('presence_level', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('competitors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_competitors_name'), 'competitors', ['name'], unique=False)
    op.create_foreign_key(None, 'competitors', 'business_profiles', ['business_id'], ['id'])
    op.drop_column('competitors', 'strengths')
    op.drop_column('competitors', 'market_share')
    op.drop_column('competitors', 'weaknesses')
    op.add_column('customer_notes', sa.Column('business_id', sa.String(), nullable=False))
    op.add_column('customer_notes', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('customer_notes', sa.Column('visit_frequency', sa.String(), nullable=True))
    op.add_column('customer_notes', sa.Column('preferred_actions', sa.Text(), nullable=True))
    op.add_column('customer_notes', sa.Column('general_notes', sa.Text(), nullable=True))
    op.add_column('customer_notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('customer_notes_customer_id_fkey', 'customer_notes', type_='foreignkey')
    op.create_foreign_key(None, 'customer_notes', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'customer_notes', 'business_profiles', ['business_id'], ['id'])
    op.drop_column('customer_notes', 'customer_id')
    op.drop_column('customer_notes', 'note')
    op.add_column('orders', sa.Column('business_id', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               nullable=False)
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'business_profiles', ['business_id'], ['id'])
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.add_column('store_notes', sa.Column('author_id', sa.String(), nullable=True))
    op.add_column('store_notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'store_notes', 'users', ['author_id'], ['id'])
    op.add_column('stores', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_stores_external_id'), 'stores', ['external_id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.drop_constraint('stores_user_id_fkey', 'stores', type_='foreignkey')
    op.drop_column('stores', 'phone')
    op.drop_column('stores', 'segment')
    op.drop_column('stores', 'opening_date')
    op.drop_column('stores', 'user_id')
    op.drop_column('stores', 'email')
    op.drop_column('stores', 'market')
    op.drop_column('stores', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('market', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('opening_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('segment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('stores_user_id_fkey', 'stores', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_external_id'), table_name='stores')
    op.drop_column('stores', 'external_id')
    op.drop_constraint(None, 'store_notes', type_='foreignkey')
    op.drop_column('store_notes', 'updated_at')
    op.drop_column('store_notes', 'author_id')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'description')
    op.add_column('orders', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'client_id')
    op.drop_column('orders', 'business_id')
    op.add_column('customer_notes', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('customer_notes', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_notes', type_='foreignkey')
    op.drop_constraint(None, 'customer_notes', type_='foreignkey')
    op.create_foreign_key('customer_notes_customer_id_fkey', 'customer_notes', 'customers', ['customer_id'], ['id'])
    op.drop_column('customer_notes', 'updated_at')
    op.drop_column('customer_notes', 'general_notes')
    op.drop_column('customer_notes', 'preferred_actions')
    op.drop_column('customer_notes', 'visit_frequency')
    op.drop_column('customer_notes', 'client_id')
    op.drop_column('customer_notes', 'business_id')
    op.add_column('competitors', sa.Column('weaknesses', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('competitors', sa.Column('market_share', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('competitors', sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competitors', type_='foreignkey')
    op.drop_index(op.f('ix_competitors_name'), table_name='competitors')
    op.drop_column('competitors', 'updated_at')
    op.drop_column('competitors', 'notes')
    op.drop_column('competitors', 'presence_level')
    op.drop_column('competitors', 'business_id')
    op.add_column('categories', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'description')
    op.drop_index(op.f('ix_busy_slots_start_time'), table_name='busy_slots')
    op.drop_index(op.f('ix_busy_slots_end_time'), table_name='busy_slots')
    op.drop_index('ix_busy_slots_business_id_start_time', table_name='busy_slots')
    op.drop_column('business_profiles', 'vertical_type')
    op.add_column('appointments', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_store_id_fkey', 'appointments', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('appointments_customer_id_fkey', 'appointments', 'customers', ['customer_id'], ['id'])
    op.drop_index('ix_appointments_business_id_start_time', table_name='appointments')
    op.create_table('assistant_configs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('greeting', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('working_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('personalized_greeting', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('logic_template', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('custom_steps', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('require_reason', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confirm_details', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('strict_guardrails', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_honesty', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_internal_alert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_lead_capture', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_emergency_phone', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name='assistant_configs_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assistant_configs_pkey'),
    sa.UniqueConstraint('business_id', name='assistant_configs_business_id_key')
    )
    op.create_index('ix_assistant_configs_id', 'assistant_configs', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='customers_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('store_clients')
    op.drop_index(op.f('ix_data_imports_id'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
