"""add_crm_config_to_business_profile

Revision ID: 6393559f145e
Revises: 1c65f6cb21a3
Create Date: 2026-03-23 23:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393559f145e'
down_revision: Union[str, None] = '1c65f6cb21a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('crm_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'crm_config')
    # ### end Alembic commands ###
