"""add_fts_index_to_knowledge_corpus

Revision ID: 648a63528efa
Revises: d5aaaa9de0ec
Create Date: 2026-06-11 17:24:21.987165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648a63528efa'
down_revision: Union[str, None] = 'd5aaaa9de0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_corpus_content_fts', 'knowledge_corpus', [sa.text("to_tsvector('spanish', content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_corpus_content_fts', table_name='knowledge_corpus', postgresql_using='gin')
    # ### end Alembic commands ###
