"""add_epic_139_prospect_segment

Revision ID: 6f219e0e3362
Revises: f8fac06b8525
Create Date: 2026-06-29 20:12:32.832888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f219e0e3362'
down_revision: Union[str, None] = 'f8fac06b8525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('prospect_segment', sa.String(), server_default='wholesale', nullable=False))
    op.create_index(op.f('ix_clients_prospect_segment'), 'clients', ['prospect_segment'], unique=False)
    op.add_column('stores', sa.Column('prospect_segment', sa.String(), server_default='wholesale', nullable=False))
    op.create_index(op.f('ix_stores_prospect_segment'), 'stores', ['prospect_segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_prospect_segment'), table_name='stores')
    op.drop_column('stores', 'prospect_segment')
    op.drop_index(op.f('ix_clients_prospect_segment'), table_name='clients')
    op.drop_column('clients', 'prospect_segment')
    # ### end Alembic commands ###
