"""add_cascade_delete_to_messaging

Revision ID: 771c9a5cf6e5
Revises: 20698eb7b14f
Create Date: 2026-03-31 16:22:25.036407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771c9a5cf6e5'
down_revision: Union[str, None] = '20698eb7b14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_client_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_business_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'business_profiles', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_business_id_fkey', 'conversations', 'business_profiles', ['business_id'], ['id'])
    op.create_foreign_key('conversations_client_id_fkey', 'conversations', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
