"""Expand StoreNote with Action Tracking fields

Revision ID: 77afb466a9ac
Revises: 5545550b117f
Create Date: 2026-06-07 14:16:27.664479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77afb466a9ac'
down_revision: Union[str, None] = '5545550b117f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_notes', sa.Column('note_type', sa.String(), nullable=False, server_default='general'))
    op.add_column('store_notes', sa.Column('is_actionable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('store_notes', sa.Column('action_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_store_notes_is_actionable'), 'store_notes', ['is_actionable'], unique=False)
    op.create_index(op.f('ix_store_notes_note_type'), 'store_notes', ['note_type'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_notes_note_type'), table_name='store_notes')
    op.drop_index(op.f('ix_store_notes_is_actionable'), table_name='store_notes')
    op.drop_column('store_notes', 'action_metadata')
    op.drop_column('store_notes', 'is_actionable')
    op.drop_column('store_notes', 'note_type')
    # ### end Alembic commands ###
