"""Expand StoreNote with Action Tracking fields

Revision ID: 77afb466a9ac
Revises: 5545550b117f
Create Date: 2026-06-07 14:16:27.664479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77afb466a9ac'
down_revision: Union[str, None] = '5545550b117f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE store_notes ADD COLUMN IF NOT EXISTS note_type VARCHAR DEFAULT 'general'")
    op.execute("ALTER TABLE store_notes ADD COLUMN IF NOT EXISTS is_actionable BOOLEAN DEFAULT false")
    op.execute("ALTER TABLE store_notes ADD COLUMN IF NOT EXISTS action_metadata JSON")
    op.execute("CREATE INDEX IF NOT EXISTS ix_store_notes_is_actionable ON store_notes (is_actionable)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_store_notes_note_type ON store_notes (note_type)")
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_store_notes_note_type")
    op.execute("DROP INDEX IF EXISTS ix_store_notes_is_actionable")
    op.execute("ALTER TABLE store_notes DROP COLUMN IF EXISTS action_metadata")
    op.execute("ALTER TABLE store_notes DROP COLUMN IF EXISTS is_actionable")
    op.execute("ALTER TABLE store_notes DROP COLUMN IF EXISTS note_type")
    # ### end Alembic commands ###
