"""Add missing B2B fields to Competitor and Appointment

Revision ID: 8baf07722e9a
Revises: 2fcd582075d6
Create Date: 2026-05-28 12:00:55.646239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8baf07722e9a'
down_revision: Union[str, None] = '2fcd582075d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_table('customers')
    op.create_index('ix_appointments_business_id_start_time', 'appointments', ['business_id', 'start_time'], unique=False)
    op.drop_constraint('appointments_customer_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'customer_id')
    op.drop_column('appointments', 'store_id')
    op.alter_column('business_profiles', 'vertical_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('BASIC', 'TRADE', name='verticaltype'),
               nullable=False,
               existing_server_default=sa.text("'BASIC'::character varying"))
    op.create_index('ix_busy_slots_business_id_start_time', 'busy_slots', ['business_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_end_time'), 'busy_slots', ['end_time'], unique=False)
    op.create_index(op.f('ix_busy_slots_start_time'), 'busy_slots', ['start_time'], unique=False)
    op.add_column('competitors', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('competitors', sa.Column('weaknesses', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'weaknesses')
    op.drop_column('competitors', 'strengths')
    op.drop_index(op.f('ix_busy_slots_start_time'), table_name='busy_slots')
    op.drop_index(op.f('ix_busy_slots_end_time'), table_name='busy_slots')
    op.drop_index('ix_busy_slots_business_id_start_time', table_name='busy_slots')
    op.alter_column('business_profiles', 'vertical_type',
               existing_type=sa.Enum('BASIC', 'TRADE', name='verticaltype'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'BASIC'::character varying"))
    op.add_column('appointments', sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_customer_id_fkey', 'appointments', 'customers', ['customer_id'], ['id'])
    op.drop_index('ix_appointments_business_id_start_time', table_name='appointments')
    op.create_table('customers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    # ### end Alembic commands ###
