"""add_reasoning_trace_to_messages

Revision ID: 8d5ac4d1ace1
Revises: bc7f56857360
Create Date: 2026-06-14 15:42:27.883513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d5ac4d1ace1'
down_revision: Union[str, None] = 'bc7f56857360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_links_business_source', table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_source_corpus_id', table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_target', table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_target_entity_id', table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_target_entity_type', table_name='knowledge_links')
    op.drop_table('knowledge_links')
    op.drop_index('ix_store_actions_business_category', table_name='store_actions')
    op.drop_index('ix_store_actions_business_objective', table_name='store_actions')
    op.drop_index('ix_store_actions_category', table_name='store_actions')
    op.drop_index('ix_store_actions_id', table_name='store_actions')
    op.drop_index('ix_store_actions_objective', table_name='store_actions')
    op.drop_table('store_actions')
    op.add_column('messages', sa.Column('reasoning_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reasoning_trace')
    op.create_table('store_actions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('MARKETING', 'COMMERCIAL', name='actioncategory'), autoincrement=False, nullable=False),
    sa.Column('objective', postgresql.ENUM('THREAT_RESPONSE', 'ANNIVERSARY', 'REPLENISHMENT', 'NEW_PRODUCT', 'RELATIONSHIP', 'GENERAL', name='actionobjective'), autoincrement=False, nullable=False),
    sa.Column('impact_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='store_actions_author_id_fkey'),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name='store_actions_business_id_fkey'),
    sa.ForeignKeyConstraint(['note_source_id'], ['store_notes.id'], name='store_actions_note_source_id_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='store_actions_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='store_actions_pkey')
    )
    op.create_index('ix_store_actions_objective', 'store_actions', ['objective'], unique=False)
    op.create_index('ix_store_actions_id', 'store_actions', ['id'], unique=False)
    op.create_index('ix_store_actions_category', 'store_actions', ['category'], unique=False)
    op.create_index('ix_store_actions_business_objective', 'store_actions', ['business_id', 'objective'], unique=False)
    op.create_index('ix_store_actions_business_category', 'store_actions', ['business_id', 'category'], unique=False)
    op.create_table('knowledge_links',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_corpus_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('link_provenance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], name='knowledge_links_business_id_fkey'),
    sa.ForeignKeyConstraint(['source_corpus_id'], ['knowledge_corpus.id'], name='knowledge_links_source_corpus_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='knowledge_links_pkey')
    )
    op.create_index('ix_knowledge_links_target_entity_type', 'knowledge_links', ['target_entity_type'], unique=False)
    op.create_index('ix_knowledge_links_target_entity_id', 'knowledge_links', ['target_entity_id'], unique=False)
    op.create_index('ix_knowledge_links_target', 'knowledge_links', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index('ix_knowledge_links_source_corpus_id', 'knowledge_links', ['source_corpus_id'], unique=False)
    op.create_index('ix_knowledge_links_business_source', 'knowledge_links', ['business_id', 'source_corpus_id'], unique=False)
    # ### end Alembic commands ###
