"""add_store_action_ledger

Revision ID: 8e7397adbb07
Revises: 21566321934a
Create Date: 2026-06-11 18:04:24.749786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7397adbb07'
down_revision: Union[str, None] = '21566321934a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MARKETING', 'COMMERCIAL', name='actioncategory'), nullable=False),
    sa.Column('objective', sa.Enum('THREAT_RESPONSE', 'ANNIVERSARY', 'REPLENISHMENT', 'NEW_PRODUCT', 'RELATIONSHIP', 'GENERAL', name='actionobjective'), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=True),
    sa.Column('note_source_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['note_source_id'], ['store_notes.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_actions_business_category', 'store_actions', ['business_id', 'category'], unique=False)
    op.create_index('ix_store_actions_business_objective', 'store_actions', ['business_id', 'objective'], unique=False)
    op.create_index(op.f('ix_store_actions_category'), 'store_actions', ['category'], unique=False)
    op.create_index(op.f('ix_store_actions_id'), 'store_actions', ['id'], unique=False)
    op.create_index(op.f('ix_store_actions_objective'), 'store_actions', ['objective'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_actions_objective'), table_name='store_actions')
    op.drop_index(op.f('ix_store_actions_id'), table_name='store_actions')
    op.drop_index(op.f('ix_store_actions_category'), table_name='store_actions')
    op.drop_index('ix_store_actions_business_objective', table_name='store_actions')
    op.drop_index('ix_store_actions_business_category', table_name='store_actions')
    op.drop_table('store_actions')
    # ### end Alembic commands ###
