"""Add features_config to BusinessProfile

Revision ID: 9179bb59d515
Revises: 10ffac29c01f
Create Date: 2026-06-24 17:35:45.259363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9179bb59d515'
down_revision: Union[str, None] = '10ffac29c01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('features_config', sa.JSON(), nullable=True))
    
    # Data migration: Populate features_config based on vertical_type
    import json
    
    basic_config = {
        "scheduling": {"enabled": True},
        "business_identity": {"enabled": True},
        "crm_suite": {"enabled": True},
        "trade_logistics": {"enabled": False},
        "sales_intelligence": {"enabled": False}
    }
    
    trade_config = {
        "scheduling": {"enabled": True},
        "business_identity": {"enabled": True},
        "crm_suite": {"enabled": True},
        "trade_logistics": {"enabled": True},
        "sales_intelligence": {"enabled": True}
    }
    
    # Safely convert to json string and run raw SQL updates on business_profiles
    op.execute(
        f"UPDATE business_profiles SET features_config = '{json.dumps(basic_config)}' WHERE vertical_type = 'BASIC'"
    )
    op.execute(
        f"UPDATE business_profiles SET features_config = '{json.dumps(trade_config)}' WHERE vertical_type = 'TRADE'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'features_config')
    # ### end Alembic commands ###
