"""Add KnowledgeCorpus

Revision ID: 92958342b182
Revises: 77afb466a9ac
Create Date: 2026-06-10 16:31:01.035983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92958342b182'
down_revision: Union[str, None] = '77afb466a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TABLE IF NOT EXISTS knowledge_corpus (
        id VARCHAR NOT NULL,
        business_id VARCHAR NOT NULL,
        entity_type VARCHAR NOT NULL,
        entity_id VARCHAR NOT NULL,
        content TEXT NOT NULL,
        embedding vector(1536),
        metadata_json JSON,
        created_at TIMESTAMP WITHOUT TIME ZONE,
        updated_at TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY (id),
        FOREIGN KEY(business_id) REFERENCES business_profiles (id)
    )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_knowledge_corpus_business_type ON knowledge_corpus (business_id, entity_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_knowledge_corpus_entity_id ON knowledge_corpus (entity_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_knowledge_corpus_entity_type ON knowledge_corpus (entity_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_knowledge_corpus_id ON knowledge_corpus (id)")
    op.execute("ALTER TABLE store_notes ALTER COLUMN is_actionable DROP NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE store_notes ALTER COLUMN is_actionable SET NOT NULL")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_corpus_id")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_corpus_entity_type")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_corpus_entity_id")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_corpus_business_type")
    op.execute("DROP TABLE IF EXISTS knowledge_corpus")
    # ### end Alembic commands ###
