"""Add KnowledgeCorpus

Revision ID: 92958342b182
Revises: 77afb466a9ac
Create Date: 2026-06-10 16:31:01.035983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92958342b182'
down_revision: Union[str, None] = '77afb466a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_corpus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_corpus_business_type', 'knowledge_corpus', ['business_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_corpus_entity_id'), 'knowledge_corpus', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_corpus_entity_type'), 'knowledge_corpus', ['entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_corpus_id'), 'knowledge_corpus', ['id'], unique=False)
    op.alter_column('store_notes', 'is_actionable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_notes', 'is_actionable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_knowledge_corpus_id'), table_name='knowledge_corpus')
    op.drop_index(op.f('ix_knowledge_corpus_entity_type'), table_name='knowledge_corpus')
    op.drop_index(op.f('ix_knowledge_corpus_entity_id'), table_name='knowledge_corpus')
    op.drop_index('ix_knowledge_corpus_business_type', table_name='knowledge_corpus')
    op.drop_table('knowledge_corpus')
    # ### end Alembic commands ###
