"""add behavioral toggles to assistant_config

Revision ID: 96f89671f45c
Revises: 9831a57e24d2
Create Date: 2026-03-17 20:48:06.426167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f89671f45c'
down_revision: Union[str, None] = '9831a57e24d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_configs', sa.Column('require_reason', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('confirm_details', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('strict_guardrails', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_configs', 'strict_guardrails')
    op.drop_column('assistant_configs', 'confirm_details')
    op.drop_column('assistant_configs', 'require_reason')
    # ### end Alembic commands ###
