"""add behavioral toggles to assistant_config

Revision ID: 96f89671f45c
Revises: 9831a57e24d2
Create Date: 2026-03-17 20:48:06.426167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f89671f45c'
down_revision: Union[str, None] = '9831a57e24d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable
    op.add_column('assistant_configs', sa.Column('require_reason', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('confirm_details', sa.Boolean(), nullable=True))
    op.add_column('assistant_configs', sa.Column('strict_guardrails', sa.Boolean(), nullable=True))

    # 2. Populate existing rows with default True
    op.execute("UPDATE assistant_configs SET require_reason = True, confirm_details = True, strict_guardrails = True")

    # 3. Alter columns to be NOT NULL if desired (optional but safer)
    op.alter_column('assistant_configs', 'require_reason', nullable=False, server_default=sa.text('true'))
    op.alter_column('assistant_configs', 'confirm_details', nullable=False, server_default=sa.text('true'))
    op.alter_column('assistant_configs', 'strict_guardrails', nullable=False, server_default=sa.text('true'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_configs', 'strict_guardrails')
    op.drop_column('assistant_configs', 'confirm_details')
    op.drop_column('assistant_configs', 'require_reason')
    # ### end Alembic commands ###
