"""add notes to appointment

Revision ID: 9831a57e24d2
Revises: 2280b1477554
Create Date: 2026-03-17 20:37:19.198179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9831a57e24d2'
down_revision: Union[str, None] = '2280b1477554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'notes')
    # ### end Alembic commands ###
