"""add_account_intelligence_fat_table

Revision ID: 9aaa08600e79
Revises: 8e7397adbb07
Create Date: 2026-06-11 18:08:11.897177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa08600e79'
down_revision: Union[str, None] = '8e7397adbb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_intelligence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('dossier_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_synthesized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_index('ix_account_intel_business_store', 'account_intelligence', ['business_id', 'store_id'], unique=False)
    op.create_index(op.f('ix_account_intelligence_id'), 'account_intelligence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_intelligence_id'), table_name='account_intelligence')
    op.drop_index('ix_account_intel_business_store', table_name='account_intelligence')
    op.drop_table('account_intelligence')
    # ### end Alembic commands ###
