"""add messaging ids to client

Revision ID: 9dc94d66cfc3
Revises: 7aaca2c7170b
Create Date: 2026-03-14 10:58:47.844699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc94d66cfc3'
down_revision: Union[str, None] = '7aaca2c7170b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('telegram_id', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('whatsapp_id', sa.String(), nullable=True))
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_clients_whatsapp_id'), 'clients', ['whatsapp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_whatsapp_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'whatsapp_id')
    op.drop_column('clients', 'telegram_id')
    # ### end Alembic commands ###
