"""add_knowledge_links_table

Revision ID: bc7f56857360
Revises: 9aaa08600e79
Create Date: 2026-06-13 18:12:29.599216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc7f56857360'
down_revision: Union[str, None] = '9aaa08600e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('source_corpus_id', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('link_provenance', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_corpus_id'], ['knowledge_corpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_links_business_source', 'knowledge_links', ['business_id', 'source_corpus_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_source_corpus_id'), 'knowledge_links', ['source_corpus_id'], unique=False)
    op.create_index('ix_knowledge_links_target', 'knowledge_links', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_target_entity_id'), 'knowledge_links', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_target_entity_type'), 'knowledge_links', ['target_entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_links_target_entity_type'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_target_entity_id'), table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_target', table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_source_corpus_id'), table_name='knowledge_links')
    op.drop_index('ix_knowledge_links_business_source', table_name='knowledge_links')
    op.drop_table('knowledge_links')
    # ### end Alembic commands ###
