"""add_vertical_type_to_business_profile

Revision ID: cffdb426ea17
Revises: 771c9a5cf6e5
Create Date: 2026-05-25 13:10:40.206571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffdb426ea17'
down_revision: Union[str, None] = '771c9a5cf6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vertical_type = sa.Enum('BASIC', 'TRADE', name='verticaltype')
    vertical_type.create(op.get_bind())
    op.add_column('business_profiles', sa.Column('vertical_type', vertical_type, server_default='BASIC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'vertical_type')
    sa.Enum(name='verticaltype').drop(op.get_bind())
    # ### end Alembic commands ###
