"""add_is_prospect_to_store_and_client

Revision ID: d2b9c075daf3
Revises: 9179bb59d515
Create Date: 2026-06-24 22:33:41.666584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2b9c075daf3'
down_revision: Union[str, None] = '9179bb59d515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_prospect', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('stores', sa.Column('is_prospect', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_prospect')
    op.drop_column('clients', 'is_prospect')
    # ### end Alembic commands ###
