"""add_vectorization_dlq

Revision ID: e12f5bf3c6b4
Revises: e91e9d7158c0
Create Date: 2026-06-19 13:50:49.550387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e12f5bf3c6b4'
down_revision: Union[str, None] = 'e91e9d7158c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vectorization_dlq',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectorization_dlq_business_id'), 'vectorization_dlq', ['business_id'], unique=False)
    op.create_index(op.f('ix_vectorization_dlq_entity_id'), 'vectorization_dlq', ['entity_id'], unique=False)
    op.create_index(op.f('ix_vectorization_dlq_entity_type'), 'vectorization_dlq', ['entity_type'], unique=False)
    op.create_index(op.f('ix_vectorization_dlq_id'), 'vectorization_dlq', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vectorization_dlq_id'), table_name='vectorization_dlq')
    op.drop_index(op.f('ix_vectorization_dlq_entity_type'), table_name='vectorization_dlq')
    op.drop_index(op.f('ix_vectorization_dlq_entity_id'), table_name='vectorization_dlq')
    op.drop_index(op.f('ix_vectorization_dlq_business_id'), table_name='vectorization_dlq')
    op.drop_table('vectorization_dlq')
    # ### end Alembic commands ###
