"""align_customer_notes_with_store_notes

Revision ID: e157629ce18d
Revises: ee378a9ef4dc
Create Date: 2026-06-17 16:10:16.740643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e157629ce18d'
down_revision: Union[str, None] = 'ee378a9ef4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_notes', sa.Column('note_type', sa.String(), nullable=False, server_default='general'))
    op.add_column('customer_notes', sa.Column('risks', sa.Text(), nullable=True))
    op.add_column('customer_notes', sa.Column('opportunities', sa.Text(), nullable=True))
    op.add_column('customer_notes', sa.Column('source_type', sa.Enum('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype'), nullable=False, server_default='MANUAL'))
    op.add_column('customer_notes', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='true'))
    op.create_index(op.f('ix_customer_notes_is_verified'), 'customer_notes', ['is_verified'], unique=False)
    op.create_index(op.f('ix_customer_notes_note_type'), 'customer_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_customer_notes_source_type'), 'customer_notes', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_notes_source_type'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_note_type'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_is_verified'), table_name='customer_notes')
    op.drop_column('customer_notes', 'is_verified')
    op.drop_column('customer_notes', 'source_type')
    op.drop_column('customer_notes', 'opportunities')
    op.drop_column('customer_notes', 'risks')
    op.drop_column('customer_notes', 'note_type')
    # ### end Alembic commands ###
