"""add_action_catalog_and_execution_fields

Revision ID: e91e9d7158c0
Revises: e157629ce18d
Create Date: 2026-06-18 15:54:32.780417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e91e9d7158c0'
down_revision: Union[str, None] = 'e157629ce18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', postgresql.ENUM('MARKETING', 'COMMERCIAL', name='actioncategory', create_type=False), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_templates_category'), 'action_templates', ['category'], unique=False)
    op.create_index(op.f('ix_action_templates_id'), 'action_templates', ['id'], unique=False)
    op.add_column('store_actions', sa.Column('assigned_to_id', sa.String(), nullable=True))
    op.add_column('store_actions', sa.Column('template_id', sa.String(), nullable=True))
    
    # Create actionstatus ENUM explicitly in PostgreSQL
    actionstatus = postgresql.ENUM('PROPOSED', 'PENDING', 'COMPLETED', 'CANCELLED', name='actionstatus')
    actionstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('store_actions', sa.Column('status', sa.Enum('PROPOSED', 'PENDING', 'COMPLETED', 'CANCELLED', name='actionstatus'), nullable=True))
    op.add_column('store_actions', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('store_actions', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.add_column('store_actions', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('store_actions', sa.Column('result_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('store_actions', sa.Column('result_unit', sa.String(), nullable=True))
    op.add_column('store_actions', sa.Column('revenue_impact', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index('ix_store_actions_assigned_status', 'store_actions', ['assigned_to_id', 'status'], unique=False)
    op.create_index('ix_store_actions_business_store_created', 'store_actions', ['business_id', 'store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_store_actions_status'), 'store_actions', ['status'], unique=False)
    op.create_foreign_key(None, 'store_actions', 'action_templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'store_actions', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###

    # --- Data Backfill for Legacy Actions ---
    bind = op.get_bind()
    businesses = bind.execute(sa.text("SELECT id FROM business_profiles")).fetchall()
    
    for biz in businesses:
        biz_id = biz[0]
        
        # Check if generic template exists for this business
        res = bind.execute(
            sa.text("SELECT id FROM action_templates WHERE business_id = :biz_id AND name = :name"),
            {"biz_id": biz_id, "name": "General Field Ingestion"}
        ).fetchone()
        
        if res:
            template_id = res[0]
        else:
            import uuid
            template_id = str(uuid.uuid4())
            bind.execute(
                sa.text(
                    "INSERT INTO action_templates (id, business_id, name, category, default_unit, description, created_at, updated_at) "
                    "VALUES (:id, :biz_id, :name, :category, :default_unit, :description, NOW(), NOW())"
                ),
                {
                    "id": template_id,
                    "biz_id": biz_id,
                    "name": "General Field Ingestion",
                    "category": "COMMERCIAL",
                    "default_unit": "tasks",
                    "description": "Legacy generic template for field notes"
                }
            )
            
        # Update existing actions for this business to point to the generic template and default to 'PENDING'
        bind.execute(
            sa.text(
                "UPDATE store_actions SET template_id = :template_id, status = 'PENDING' "
                "WHERE business_id = :biz_id"
            ),
            {"template_id": template_id, "biz_id": biz_id}
        )

    # Set status column to NOT NULL after populating existing rows
    op.alter_column('store_actions', 'status', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_actions', type_='foreignkey')
    op.drop_constraint(None, 'store_actions', type_='foreignkey')
    op.drop_index(op.f('ix_store_actions_status'), table_name='store_actions')
    op.drop_index('ix_store_actions_business_store_created', table_name='store_actions')
    op.drop_index('ix_store_actions_assigned_status', table_name='store_actions')
    op.drop_column('store_actions', 'revenue_impact')
    op.drop_column('store_actions', 'result_unit')
    op.drop_column('store_actions', 'result_value')
    op.drop_column('store_actions', 'resolved_at')
    op.drop_column('store_actions', 'resolution_notes')
    op.drop_column('store_actions', 'due_date')
    op.drop_column('store_actions', 'status')
    op.drop_column('store_actions', 'template_id')
    op.drop_column('store_actions', 'assigned_to_id')
    op.drop_index(op.f('ix_action_templates_id'), table_name='action_templates')
    op.drop_index(op.f('ix_action_templates_category'), table_name='action_templates')
    op.drop_table('action_templates')
    
    # Drop actionstatus ENUM explicitly in PostgreSQL
    actionstatus = postgresql.ENUM('PROPOSED', 'PENDING', 'COMPLETED', 'CANCELLED', name='actionstatus')
    actionstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
