"""add_data_provenance_fields

Revision ID: ee378a9ef4dc
Revises: 8d5ac4d1ace1
Create Date: 2026-06-17 14:01:35.043080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee378a9ef4dc'
down_revision: Union[str, None] = '8d5ac4d1ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    # Handle Enums safely
    existing_enums = [e['name'] for e in inspector.get_enums()]
    
    if 'datasourcetype' not in existing_enums:
        datasourcetype = postgresql.ENUM('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype')
        datasourcetype.create(bind)
        
    if 'actioncategory' not in existing_enums:
        actioncategory = postgresql.ENUM('MARKETING', 'COMMERCIAL', name='actioncategory')
        actioncategory.create(bind)
        
    if 'actionobjective' not in existing_enums:
        actionobjective = postgresql.ENUM('THREAT_RESPONSE', 'ANNIVERSARY', 'REPLENISHMENT', 'NEW_PRODUCT', 'RELATIONSHIP', 'GENERAL', name='actionobjective')
        actionobjective.create(bind)

    if not inspector.has_table('store_actions'):
        op.create_table('store_actions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('business_id', sa.String(), nullable=False),
        sa.Column('store_id', sa.String(), nullable=False),
        sa.Column('author_id', sa.String(), nullable=True),
        sa.Column('category', postgresql.ENUM('MARKETING', 'COMMERCIAL', name='actioncategory', create_type=False), nullable=False),
        sa.Column('objective', postgresql.ENUM('THREAT_RESPONSE', 'ANNIVERSARY', 'REPLENISHMENT', 'NEW_PRODUCT', 'RELATIONSHIP', 'GENERAL', name='actionobjective', create_type=False), nullable=False),
        sa.Column('impact_level', sa.String(), nullable=True),
        sa.Column('note_source_id', sa.String(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
        sa.ForeignKeyConstraint(['note_source_id'], ['store_notes.id'], ),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_store_actions_business_category', 'store_actions', ['business_id', 'category'], unique=False)
        op.create_index('ix_store_actions_business_objective', 'store_actions', ['business_id', 'objective'], unique=False)
        op.create_index(op.f('ix_store_actions_category'), 'store_actions', ['category'], unique=False)
        op.create_index(op.f('ix_store_actions_id'), 'store_actions', ['id'], unique=False)
        op.create_index(op.f('ix_store_actions_objective'), 'store_actions', ['objective'], unique=False)

    # Check and add columns safely
    columns = [c['name'] for c in inspector.get_columns('competitors')]
    if 'source_type' not in columns:
        op.add_column('competitors', sa.Column('source_type', postgresql.ENUM('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype', create_type=False), nullable=False, server_default='MANUAL'))
        op.create_index(op.f('ix_competitors_source_type'), 'competitors', ['source_type'], unique=False)
    if 'is_verified' not in columns:
        op.add_column('competitors', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='true'))
        op.create_index(op.f('ix_competitors_is_verified'), 'competitors', ['is_verified'], unique=False)

    columns = [c['name'] for c in inspector.get_columns('orders')]
    if 'source_type' not in columns:
        op.add_column('orders', sa.Column('source_type', postgresql.ENUM('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype', create_type=False), nullable=False, server_default='MANUAL'))
        op.create_index(op.f('ix_orders_source_type'), 'orders', ['source_type'], unique=False)
    if 'is_verified' not in columns:
        op.add_column('orders', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='true'))
        op.create_index(op.f('ix_orders_is_verified'), 'orders', ['is_verified'], unique=False)

    columns = [c['name'] for c in inspector.get_columns('store_notes')]
    if 'source_type' not in columns:
        op.add_column('store_notes', sa.Column('source_type', postgresql.ENUM('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype', create_type=False), nullable=False, server_default='MANUAL'))
        op.create_index(op.f('ix_store_notes_source_type'), 'store_notes', ['source_type'], unique=False)
    if 'is_verified' not in columns:
        op.add_column('store_notes', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='true'))
        op.create_index(op.f('ix_store_notes_is_verified'), 'store_notes', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_notes_source_type'), table_name='store_notes')
    op.drop_index(op.f('ix_store_notes_is_verified'), table_name='store_notes')
    op.drop_column('store_notes', 'is_verified')
    op.drop_column('store_notes', 'source_type')
    op.drop_index(op.f('ix_orders_source_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_verified'), table_name='orders')
    op.drop_column('orders', 'is_verified')
    op.drop_column('orders', 'source_type')
    op.drop_index(op.f('ix_competitors_source_type'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_is_verified'), table_name='competitors')
    op.drop_column('competitors', 'is_verified')
    op.drop_column('competitors', 'source_type')
    op.drop_index(op.f('ix_store_actions_objective'), table_name='store_actions')
    op.drop_index(op.f('ix_store_actions_id'), table_name='store_actions')
    op.drop_index(op.f('ix_store_actions_category'), table_name='store_actions')
    op.drop_index('ix_store_actions_business_objective', table_name='store_actions')
    op.drop_index('ix_store_actions_business_category', table_name='store_actions')
    op.drop_table('store_actions')
    
    # Drop the enum type
    datasourcetype = postgresql.ENUM('MANUAL', 'AI_EXTRACTED', 'INTEGRATION', name='datasourcetype')
    datasourcetype.drop(op.get_bind())
    # ### end Alembic commands ###
