"""add_delivery_zip_codes_to_store

Revision ID: f25e505ad495
Revises: d2b9c075daf3
Create Date: 2026-06-25 17:08:39.691351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25e505ad495'
down_revision: Union[str, None] = 'd2b9c075daf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('delivery_zip_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'delivery_zip_codes')
    # ### end Alembic commands ###
