"""add_epic_138_referral_columns

Revision ID: f8fac06b8525
Revises: 3edfac0639c7
Create Date: 2026-06-29 20:05:16.093602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8fac06b8525'
down_revision: Union[str, None] = '3edfac0639c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_store_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('old_store_id', sa.String(), nullable=True),
    sa.Column('new_store_id', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_store_history_id'), 'client_store_history', ['id'], unique=False)
    op.add_column('stores', sa.Column('assigned_store_id', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('requested_product_id', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('requested_quantity', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('potential_value', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('referred_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'stores', 'products', ['requested_product_id'], ['id'])
    op.create_foreign_key(None, 'stores', 'stores', ['assigned_store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'referred_at')
    op.drop_column('stores', 'potential_value')
    op.drop_column('stores', 'requested_quantity')
    op.drop_column('stores', 'requested_product_id')
    op.drop_column('stores', 'assigned_store_id')
    op.drop_index(op.f('ix_client_store_history_id'), table_name='client_store_history')
    op.drop_table('client_store_history')
    # ### end Alembic commands ###
