"""change_assigned_to_id_fk_to_clients

Revision ID: fe412c1df3d4
Revises: e12f5bf3c6b4
Create Date: 2026-06-20 12:03:58.067767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe412c1df3d4'
down_revision: Union[str, None] = 'e12f5bf3c6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('store_actions_assigned_to_id_fkey'), 'store_actions', type_='foreignkey')
    # Set existing assignee IDs to NULL since they refer to user IDs and not client IDs
    op.execute("UPDATE store_actions SET assigned_to_id = NULL")
    op.create_foreign_key(None, 'store_actions', 'clients', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_actions', type_='foreignkey')
    op.create_foreign_key(op.f('store_actions_assigned_to_id_fkey'), 'store_actions', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###
