"""add_structured_address_and_postal_codes

Revision ID: fe805ab06981
Revises: f25e505ad495
Create Date: 2026-06-25 17:17:51.580653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe805ab06981'
down_revision: Union[str, None] = 'f25e505ad495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('colonia', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_codes_id'), 'postal_codes', ['id'], unique=False)
    op.create_index(op.f('ix_postal_codes_zip_code'), 'postal_codes', ['zip_code'], unique=False)
    
    op.add_column('stores', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('colonia', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('municipality', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('city', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('state', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('stores', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_stores_zip_code'), 'stores', ['zip_code'], unique=False)

    # Data Migration: Parse existing unstructured address strings
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT id, address FROM stores"))
    for row in result.fetchall():
        store_id, legacy_address = row
        if legacy_address:
            # Heuristic split by comma
            parts = [p.strip() for p in legacy_address.split(",")]
            street = parts[0] if len(parts) > 0 else legacy_address
            city = parts[1] if len(parts) > 1 else None
            state = parts[2] if len(parts) > 2 else (parts[1] if len(parts) == 2 else None)
            
            # Detect ZIP from text like "CP 04210" or "04210"
            zip_code = None
            import re
            zip_match = re.search(r"\b\d{5}\b", legacy_address)
            if zip_match:
                zip_code = zip_match.group(0)
            
            # Remove ZIP/CP string part from street/city/state if present
            if zip_code:
                if city:
                    city = re.sub(r"\(?CP\s*\d{5}\)?", "", city).strip()
                if state:
                    state = re.sub(r"\(?CP\s*\d{5}\)?", "", state).strip()
                street = re.sub(r"\(?CP\s*\d{5}\)?", "", street).strip()

            bind.execute(
                sa.text(
                    "UPDATE stores SET street_address = :street, city = :city, state = :state, zip_code = :zip_code, country = 'México' WHERE id = :id"
                ),
                {"street": street, "city": city, "state": state, "zip_code": zip_code, "id": store_id}
            )

    # Drop legacy address column
    op.drop_column('stores', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('address', sa.String(), nullable=True))
    
    # Reconstruct unstructured address strings from component columns
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT id, street_address, city, state, zip_code FROM stores"))
    for row in result.fetchall():
        store_id, street, city, state, zip_code = row
        addr_parts = []
        if street:
            addr_parts.append(street)
        if city:
            addr_parts.append(city)
        if zip_code:
            addr_parts.append(f"CP {zip_code}")
        if state:
            addr_parts.append(state)
        
        legacy_addr = ", ".join(addr_parts) if addr_parts else None
        if legacy_addr:
            bind.execute(
                sa.text("UPDATE stores SET address = :address WHERE id = :id"),
                {"address": legacy_addr, "id": store_id}
            )

    op.drop_index(op.f('ix_stores_zip_code'), table_name='stores')
    op.drop_column('stores', 'country')
    op.drop_column('stores', 'zip_code')
    op.drop_column('stores', 'state')
    op.drop_column('stores', 'city')
    op.drop_column('stores', 'municipality')
    op.drop_column('stores', 'colonia')
    op.drop_column('stores', 'street_address')
    
    op.drop_index(op.f('ix_postal_codes_zip_code'), table_name='postal_codes')
    op.drop_index(op.f('ix_postal_codes_id'), table_name='postal_codes')
    op.drop_table('postal_codes')
    # ### end Alembic commands ###
